
import java.awt.List;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author
 */
public class Gui extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    ArrayList<Integer> list_code;
    int tries = 3;
    public int getRandomNumber(int min, int max) {
		return (int)(Math.random() * ((max - min) + 1)) + min;
	}
    public Gui() {
        initComponents();
        setSize(1200, 900);
        //setVisible(true);
        Set<Integer> hash_code = new HashSet<Integer>();
        do{
            hash_code.add(getRandomNumber(0,9));
        }while(hash_code.size() != 4);
        list_code = new ArrayList<Integer>(hash_code);
        
        for(int i : list_code){
            System.out.print(i);
        }
        System.out.println("");
        Set<Integer> hash_hint1 = new HashSet<Integer>();
        do{
            hash_hint1.add(getRandomNumber(0,9));
        }while(hash_hint1.size() != hash_code.size());
        int count = 0;
        ArrayList<Integer> list_hint1 = new ArrayList<Integer>(hash_hint1);
        for(int i=0;i<list_code.size();i++){
            for(int j=0;j<list_hint1.size();j++){
                if(list_code.get(i) == list_hint1.get(j)){
                    count++;
                }
            }
        }
        String l1="First Hint: ";
        for(int i : list_hint1){
            l1 += i;
        }
        l1+="        Correct Numbers: ";
        l1+= count;
        jLabel3.setText(l1);
        count=0;
                System.out.println("");
        Set<Integer> hash_hint2 = new HashSet<Integer>();
        do{
            hash_hint2.add(getRandomNumber(0,9));
        }while(hash_hint2.size() != hash_code.size());
        ArrayList<Integer> list_hint2 = new ArrayList<Integer>(hash_hint2);
        for(int i=0;i<list_code.size();i++){
            for(int j=0;j<list_hint2.size();j++){
                if(list_code.get(i) == list_hint2.get(j)){
                    count++;
                }
            }
        }
        String l2="Second Hint: ";
        for(int i : list_hint2){
            l2 += i;
        }
        l2+="        Correct Numbers: ";
        l2+= count;
        jLabel4.setText(l2);
        count=0;
                System.out.println("");
        Set<Integer> hash_hint3 = new HashSet<Integer>();
        do{
            hash_hint3.add(getRandomNumber(0,9));
        }while(hash_hint3.size() != hash_code.size());
        ArrayList<Integer> list_hint3 = new ArrayList<Integer>(hash_hint3);
        for(int i=0;i<list_code.size();i++){
            for(int j=0;j<list_hint3.size();j++){
                if(list_code.get(i) == list_hint3.get(j)){
                    count++;
                }
            }
        }
        String l3="Third Hint: ";
        for(int i : list_hint3){
            l3 += i;
        }
        l3+="        Correct Numbers: ";
        l3+= count;
        jLabel5.setText(l3);
        count=0;
                System.out.println("");
        Set<Integer> hash_hint4 = new HashSet<Integer>();
        do{
            hash_hint4.add(getRandomNumber(0,9));
        }while(hash_hint4.size() != hash_code.size());
        ArrayList<Integer> list_hint4 = new ArrayList<Integer>(hash_hint4);
        for(int i=0;i<list_code.size();i++){
            for(int j=0;j<list_hint4.size();j++){
                if(list_code.get(i) == list_hint4.get(j)){
                    count++;
                }
            }
        }
        String l4="Fourth Hint: ";
        for(int i : list_hint4){
            l4 += i;
        }
        l4+="        Correct Numbers: ";
        l4+= count;
        jLabel6.setText(l4);
        count=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MICROSOFT STUDENT COMMUNITY CODEBREAKER ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(510, 300, 350, 17);

        jTextField1.setBackground(new java.awt.Color(0, 204, 0));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(590, 450, 94, 79);

        jTextField2.setBackground(new java.awt.Color(0, 204, 204));
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(710, 450, 94, 79);

        jTextField3.setBackground(new java.awt.Color(255, 153, 0));
        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(820, 450, 94, 79);

        jTextField4.setBackground(new java.awt.Color(255, 51, 0));
        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(480, 450, 94, 79);

        jLabel2.setFont(new java.awt.Font("Utsaah", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CAN YOU BREAK THE CODE?");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(480, 380, 430, 56);

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("BREAK THE CODE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(480, 540, 430, 72);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 450, 430, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("jLabel3");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 470, 430, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("jLabel3");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 490, 430, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("jLabel3");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 510, 430, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AMA University Microsoft Student Community Logo v2.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-100, 0, 1350, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(tries != 0){
            tries --;
            int n1 = Integer.parseInt(jTextField1.getText());
            int n2 = Integer.parseInt(jTextField2.getText());
            int n3 = Integer.parseInt(jTextField3.getText());
            int n4 = Integer.parseInt(jTextField4.getText());
            ArrayList<Integer> solution = new ArrayList<Integer>();
            solution.add(n1);
            solution.add(n2);
            solution.add(n3);
            solution.add(n4);
            int correct =0;
            for(int i=0;i<list_code.size();i++){
                for(int j=0;j<solution.size();j++){
                    if(list_code.get(i) == solution.get(j)){
                        correct++;
                    }
                }
            }
            if(correct == 4){
                JOptionPane.showMessageDialog(null, "YOU WON!!!!");
            }else{
                JOptionPane.showMessageDialog(null, "YOU ONLY HAVE: "+tries+" tries");
            }
        }else{
            String sol = "";
            for(int i=0;i<list_code.size();i++){
                sol += String.valueOf(list_code.get(i));
            }
            JOptionPane.showMessageDialog(null, "YOU LOST!!!! The Correct Answer is: "+sol);
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
